### ISSUE TITLE
Secret Ballot builds with errors

### ISSUE THREAD

**Issue by rebekahkim** [oasislabs/tutorials#40]
**Description of the bug**
When installing app dependencies (`oasis build` in `app/`), it builds but with lots of errors/warnings.

**Steps to reproduce**
1. 'oasis build` in `app/`
2. It builds but with errors
3. See error

```
Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/App.vue:1:1:
> 1 | <template>
    | ^
  2 |   <v-app id="app">
  3 |     <v-toolbar
  4 |       id="SecretBallot_Toolbar"


1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Confirmation.vue:1:1:
> 1 | <template>
    | ^
  2 |   <v-container id="Confirm_Container" fill-height>
  3 |     <v-card
  4 |       id="Confirm_Card"


1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Results.vue:1:1:
> 1 | <template>
    | ^
  2 |   <v-container id="Results_Container" fill-height>
  3 |     <v-card
  4 |       id="Results_Card"


1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Vote.vue:1:1:
> 1 | <template>
    | ^
  2 |   <v-container id="Vote_Container" fill-height>
  3 |     <v-card
  4 |       id="Vote_Card"


1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Welcome.vue:1:1:
> 1 | <template>
    | ^
  2 |   <v-container id="Welcome_Container" fill-height>
  3 |     <v-card
  4 |       id="Welcome_Card"


1 error found.
```

**Expected behavior**
Clean build

**Environment**
 - OS: macOS Mojave

**Comment by naheed** [comment]
is this issue replicated Nikhil?

**Comment by sharmaster96** [comment]
Yes.They are known errors. They do not affect functionality.
